#!/usr/bin/python

import start
from oslo.config import cfg
from multiprocessing import Process

CONF = cfg.CONF
CONF.import_opt('compute_processes', 'nova.compute.simulator')

if __name__ == "__main__":
    workers = []
    for i in xrange(CONF.compute_processes):
        host = '%s-%s' % (CONF.host, str(i + 1))
        p = Process(target=start.start, args=(host, ))
        p.start()
        workers.append(p)

    try:
        for worker in workers:
            worker.join()
    except KeyboardInterrupt:
        for worker in workers:
            worker.terminate()
            worker.join()